const slider_details = [
  {
    id: 1,
    title: "Introduction to Zest Protocol",
    desc: "Zest Protocol is a decentralized lending platform on Bitcoin, offering transparent, on-chain credit solutions. It connects borrowers and lenders directly, enabling access to Bitcoin-native capital markets with secure, efficient, and permissionless financial services.This Alpha-hub quest is an independently curated educational journey, designed by Intract to enhance your understanding and engagement with interesting and innovative web3 projects.",
    count: 707,
    img: "/alpha/slider_1.png",
  },
  {
    id: 2,
    title: "Introduction to Squid Router",
    desc: "SquidRouter is a Web3 dApp enabling seamless cross-chain swaps and liquidity management. It connects multiple blockchains, allowing users to trade assets efficiently and securely across diverse networks, enhancing interoperability and optimizing decentralized finance (DeFi) experiences.This Alpha-hub quest is an independently curated educational journey, designed by Intract to enhance your understanding and engagement with interesting and innovative web3 projects.",
    count: 738,
    img: "/alpha/slider_2.png",
  },
  {
    id: 3,
    title: "Exploring Sui Network",
    desc: "Explore the Sui Network, a decentralized blockchain platform designed for high-speed, secure transactions. It offers scalable infrastructure for dApps, smart contracts, and DeFi, enabling developers and users to create and engage in innovative digital solutions efficiently.This Alpha-hub quest is an independently curated educational journey, designed by Intract to enhance your understanding and engagement with interesting and innovative web3 projects.",
    count: 1829,
    img: "/alpha/slider_3.png",
  },
  {
    id: 4,
    title: "Introduction To Farcaster",
    desc: "Farcaster is a decentralized social network built on open protocols. It empowers users to own their identity, content, and social connections, giving them control over their online presence in a secure and transparent way.This Alpha-hub quest is an independently curated educational journey, designed by Intract to enhance your understanding and engagement with interesting and innovative web3 projects.",
    count: 3018,
    img: "/alpha/slider_4.jpg",
  },
  {
    id: 5,
    title: "Introduction to Mind Network",
    desc: "Mind Network is a cutting-edge Web3 platform leveraging Fully Homomorphic Encryption (FHE) to secure data and transactions. It offers enhanced privacy, enabling computation on encrypted data without decryption, and is developing a suite of interconnected products for a safer, decentralized internet.This Alpha-hub quest is an independently curated educational journey, designed by Intract to enhance your understanding and engagement with interesting and innovative web3 projects.",
    count: 4548,
    img: "/alpha/slider_5.jpg",
  },
  {
    id: 6,
    title: "Introduction to DeBank",
    desc: "DeBank is a comprehensive dashboard designed for tracking and managing your assets within the world of DeFi. It offers insights into various DeFi protocols, stablecoins, exchanges, and lending platforms, empowering you to make informed decisions about your crypto portfolio.This Alpha-hub quest is an independently curated educational journey, designed by Intract to enhance your understanding and engagement with interesting and innovative web3 projects.",
    count: 2249,
    img: "/alpha/slider_6.png",
  },
  {
    id: 7,
    title: "Navigating Bungee and Jumper Exchanges",
    desc: "Bungee Exchange is a cross-chain swap platform optimizing token exchanges across blockchains. Jumper Exchange, powered by LI.FI, aggregates liquidity for multi-chain bridging and swapping, simplifying asset transfers.This Alpha-hub quest is an independently curated educational journey, designed by Intract to enhance your understanding and engagement with interesting and innovative web3 projects.",
    count: 1038,
    img: "/alpha/slider_7.jpg",
  },
];

const narrative_detail = [
  {
    id: 1,
    title: "Exploring Farcaster",
    desc: "Farcaster is a decentralized social network built on OP, enabling users to own their identity and data. Users can share updates, follow others, engage in conversations, and interact with decentralized applications, fostering an open and user-controlled social experience.",
    count: "1.4k",
    xp: "230",
    quest: 4,
    questList: [
      {
        id: 1,
        img: "/alpha/narrative1.png",
        chain: "Base",
        chainLogo: "/alpha/base.webp",
        task: "4",
        xp: "70",
        title: "$DEGEN Meets Orbit",
      },
      {
        id: 2,
        img: "/alpha/narrative2.png",
        chain: "OP Mainnet",
        chainLogo: "/alpha/optimism.png",
        task: "4",
        xp: "40",
        title: "Introduction to Farcaster",
      },
      {
        id: 3,
        img: "/alpha/narrative3.png",
        chain: "OP Mainnet",
        chainLogo: "/alpha/optimism.png",
        task: "5",
        xp: "50",
        title: "Follow People on Warpcast",
      },
      {
        id: 4,
        img: "/alpha/narrative4.png",
        chain: "Ethereum",
        chainLogo: "/alpha/eth.png",
        task: "4",
        xp: "40",
        title: "Explore Farcaster Dapps",
      },
    ],
  },
  {
    id: 2,
    title: "Exploring Lens Protocol",
    desc: "Lens Protocol is a decentralized social graph that empowers developers to create social media applications on the blockchain. It ensures data ownership, privacy, and interoperability, enabling users to control their content and identities while fostering innovation in decentralized social networking.",
    count: "753",
    xp: "70",
    quest: 3,
    questList: [
      {
        id: 1,
        img: "/alpha/narrative5.png",
        chain: "Ethereum",
        chainLogo: "/alpha/eth.png",
        task: "3",
        xp: "30",
        title: "Introduction to Lens Protocol",
      },
      {
        id: 2,
        img: "/alpha/narrative6.png",
        chain: "Polygon Mainnet",
        chainLogo: "/alpha/polygon.png",
        task: "2",
        xp: "20",
        title: "Exploring Dapps Lensfrens",
      },
      {
        id: 3,
        img: "/alpha/narrative7.png",
        chain: "Polygon Mainnet",
        chainLogo: "/alpha/polygon.png",
        task: "2",
        xp: "20",
        title: "Exploring Dapps Lenstube",
      },
    ],
  },
  {
    id: 3,
    title: "Exploring GRASS",
    desc: "Grass is a network of over 2 million people who are rewarded for helping AI developers access the internet. Its goal is to prevent the concentration of AI by allowing ordinary people to play a part and share in the benefits of its growth.",
    count: "1.4k",
    xp: "40",
    quest: 1,
    questList: [
      {
        id: 1,
        img: "/alpha/narrative8.png",
        chain: "",
        chainLogo: "",
        task: "2",
        xp: "40",
        title: "Introduction to Grass",
      },
    ],
  },
];

export { slider_details, narrative_detail };
